version: '3.9'
services:
  web:
    restart: on-failure
    build: ./web
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.02'
          memory: 50M
        reservations:
          cpus: '0.01'
          memory: 20M
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 100M
        reservations:
          cpus: '0.1'
          memory: 50M
    depends_on:
    - web